
language: node_js

cache:
    directories:
        - node_modules

deploy:
    provider: firebase
    token:
        secure: "FYBbkvW282KgeLNgn4fT35w8sewdeYL967bTKc5ZZNuTYc4T2KVezUHzWV3nnjF4VDL5arnutF3haquAfUu+0Ptbx8HNqxlcsrqk89z33P/NmoImH1KFYrKjzp8f/816ByhrWXm8erWKDyYNjEqwOT8/hLbBlPr0/0li9OISRBB5F8fWDyh5xPKl3cou+5O2eczK3vPyEjcCqUHUigGQ6gKiTEPWXvy+O9CfAadn/rjyWKxBWWa0cDFfG9Np90BhiKfJeggPvfJoH4kqicXIJjWytAof/mESrbkjKOKfZxH/nKbhSkAQF+3u+XMblUwcfzBeylYtWncpl1lKj6BxRKnZ8Hb6s5n5Od24cCidYUnBYTXnNbLPiOR/S2Q7DAbcG8HfFSkgxhp12fNU5gqbf8/UVBywXN42lfs3Kz1KeE6N/3ye9xXnAvszUEC5YJt97XkQ8noIKRWHlOy6k+fllZkox/4pfSJP9D/J3FMOgQyZUQu2nMGTw1lRR1bbUAJA11Etk2S2wiw/xEoL0PcMb/6UOxGt0TSxcJMuu7DEbr+3pn3631MK4AmEgKA9ZQmD5dckjTDQT7pbIfjdid3tdAHoi7Z+9oi0kARYvvL1wzVxjmztRgl7xQPwI2v1uzNYC0AmVQUCLRA7wMnP5Lt4PaiXxeulRn+livOtcAkGoes="
    skip_cleanup: true
    on:
        branch:
            - master
