
language: node_js

cache:
    directories:
        - node_modules

env:
    global:
        - secure: "KD9TocaXaFSGruQapMGwmX5MiQfC5Mm8GHGb/jbKmUTyyPKA4TpPS2GwsnzzDLZnXk6L3B9fRfwnl5lDjGcX7SVcVNI3E9zXWqYS31DBDaDHXyHO/rj9RMsL9940SmHjohdLQS1WiUFzHKQqtkPyoValbMW7B12OjvNOPxRyh1QAu/Mhb2xC2lDIItJGGBW5lDLmcAYlWa8dKDSFux8muvjErHsPwugqcDihm07fNVuTBZW1P6nb1PgWPPTB5vYjKG2qvVGFxav38aVKccWC5WAaySrv66T6vOU00eYph8i8Ja8s/flxHJ5WgbCbs9sBoS4/x6TJ0RZ0IM7GMAf1oyu0SXjUvr7ZXfLU9BljbB/zicNF1QZ7OnSs20f5smviMemG9pezsuK0wepw9BJZugav/+y/9ljlrlZRvGyjlswrLM3J3b+1kTvZXLUmAXJftj+cK+UN9jEySkjgdtaudXAjLTOL3nvQITEy+wed5pWq3O7aldfhH/7YanoXcmDrbQteqWveBbrac5yzaEHXt/cukypRc++4Kdv6BhUBKkNY1CpW0F2wdObkuaV+DOxdKZAb1PkV7xb8tIj793F9HvphdhvXsq9PX+dlsPo7PlWOCV5EdHUFGJR4x+rgTk2gBsXbfY7fL6uZdwCUz+ia9KgmJZDVI34YlvodGqydK3c="

deploy:
    provider: script
    script: npm run deploy -- --token=${FIREBASE_TOKEN}
    skip_cleanup: true
    on:
        branch:
            - master
