
language: node_js

cache:
    directories:
        - node_modules

deploy:
    provider: firebase
    token:
        secure: sguN2HMf9Mcvb+6goJXBT63Dc+nWrJ3pJBnDKjtJWwFDFvTtm4Y/fd1Bq/9LTSuh6PDkSqRfWdMf1jxOMXWrXxGoQTA6Y8yFHgg1s/bUqYaU0bbFZPvAviGfxsaYcWhhcWf8Y/GxclASnUmFh3FI8HG/NnVuFjoGIkWScKsHlKqVmc6IUcfHTvxNYu5WTMsMeSB8b7lkoxeMsMHWX+D31me5H42DhEhc/X1CDKRJ8KEpxa8aUF+S2W6+i3ICj9EFGGr3+2/LKNSzZWSDLv04Led1RKhXx0UP1qUPxWZVWswVReQV80XmZbWSePJP3B5+8s0q9gIvMMHGMLslhw0EBshbIrpsnV5HsROhwogWu/jtgGYZu/g3n0VGxdv8QV/Zvi8HtipeHRFLxNXtnM2D6cFdnZ3Wp9nPuWvc8EBEydU1E2FznohZPlqzl+WzdHFBHT5Go55/mCJxtNPmIm9ExXDx0LZuM3Fd1XTFtg2aNizZ6ETxACpGiQkqzVdpNxPsZt8pLIartaNLGveso2Nv0ejc7ex2bdiiOmaxI+mkEofjsQpm40TWgMXFVTslw9meiB9xkuZfC7JCwJB8H4Nc9SNqfPk95+0KPOQjXeDE7hKbdsx//xG6LKgGvSc971q1LreqJE1pFhe4sTgsmxXNGybJjVfsAqnkM1AyATRImz4=
    project: readr-60929
    skip_cleanup: true
    on:
        branch:
            - master
