
language: node_js

cache:
    directories:
        - node_modules

env:
    global:
        - secure: "EfYIFW8Fj17gtaES80wMhoVk+nUo++Hjbc8DNlb/bXOCukerRNJ/v4tpWTZgTmbb4ladrbiMvhEKHwdQzcsHupkRVM3rrm1gDEUUM60aWhwVAOh+9E8b6j2g2RNyKndvxIDOCOblvqRNofoz1yHQ2MbqZos8y74Tu+fR1IZ01aEWaUxMgauMVdDlMHMh2v6hd2GV3XUDxw2tcIafMOeuROsu68qnA74ZSgPxUT3ekEPkQR31eLU19xLDqTII0H6/wfOKoIw1EtF4meCHJr0PBjHBa7C1D+9DuaTdT27vq0GiX74XDZTWM8mLj3/iRT3RjgBkKokuOgj0sYL6/jsKRx8l9Fuujrh9M4c4YXhnOKAnwyIViwEiwd6Xt59SHGfbk/b34Dk4E+D43Wchn66d2OVVSkMA+rOGhypc0t2xntUYdePULBgwGdLgMyvFPWiGuI8awdET+H0tlxnxN7LxBmntc6Gdif7mOBX6mqc1mwxm7hQdDzQWtEdWgF+5jP95Soyhqi9M/35SXPJL3zlGYsMyQrSI2puBtHtMoQkqnWXWAmGdCEw/lJyBFLUuGcbhiXBwOTyNaKq0yjONSEba/RxIOhyt4VQl+NG+OMoO2glyoByFU9E9aY0f5C5Qsv4R0dZU/3ZCBo8RXOElT9Q9m0UasxB5RbCkm9GZNKKC1a0="

deploy:
    provider: script
    script: $(npm bin)/firebase deploy --only=function --token=$FIREBASE_TOKEN
    skip_cleanup: true
    on:
        branch:
            - master
