
language: node_js

cache:
    directories:
        - node_modules

deploy:
    provider: firebase
    token:
        secure: "kh6Xv73gI8E7GTEBR5C1F7C+xlaZUTOm5FhJOKBjYwxVfNOHnr5XyZFJ9JzX3dFPlaZ6drajwhql1POB4gTDM8Uztb1eA900p3LneOT5gS1W5zKyiQ4ytEmsSPi4G+W2px2Rx03WZnc3hdukP5nASWKGMyiB4CpTGR+Lok5Ofei9+U/goVvqUQ/LEA2hS+ZM2nrX26majWpq620mVg6KE/OG5+wgXoanrsERH1T1A6eplvEVY1yIeadEAYjq0kYIhtmTzYllEQd7m4YQ+/walmcTzpAtQGyss7aDWZFNt1L/WlpXrbsFbPDQbZm2JzVQF587YScD5dsHHZPD6qhJeqot3/TNzixJlx+AHwWP5E0y+3b9M9sHUIG28n3QPqLdDI496rZOndO466ROSCAUhP3fwCKQJY6RgEL7StQqQEh0uH9MrpygN2uPLnHey/Z/kDAsj/pojxfd71hM731IYZdrzrKROpvXZAa4xRskFX7KAYQR0jYc4o4Nbdc82pePz6EDN6J5XbN1c9e0aITc+usM7h4P4uBaudgJ1VU79F7yhpvOpab3iOEyNjqMkhLlToBL2hCmT6PgyAFz09z0WvFgDzNOCF3TijLnfCDf0fZcECRVgV/fUOqbgc/yzMLCup6FaeSo7Hy2ujWXm4zvUQePiFomJ3eRfHNtSzwqYUg="
    project: readr-60929
    skip_cleanup: true
    on:
        branch:
            - master
