#!/usr/bin/env node

const fetchContents = require('./functions/fetch-contents/');
const url = process.argv[2];

if (!url) {
    console.warn(`
Please pass in a URL:

$ ./fetch http://example.com

`);
    process.exit(1);
}

fetchContents(url, console.log.bind(console));
