#!/usr/bin/env node

const fetch = require('./functions/').fetchContents;
const url = process.argv[2];

if (!url) {
    console.warn(`
Please pass in a URL:

$ ./fetch http://example.com

`);
    process.exit(1);
}

fetch({
    body: JSON.stringify({ url }),
}, null, console.log.bind(console));
